scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'grafana'
    scrape_interval: 1m
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
  - job_name: 'config-service'
    scrape_interval: 10s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'config-service:9999' ]
  - job_name: 'discovery-service-1'
    scrape_interval: 10s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'discovery-service-1:8761' ]
  - job_name: 'discovery-service-2'
    scrape_interval: 10s
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'discovery-service-1:8762' ]
  - job_name: 'gateway-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['gateway-service:9098']
  - job_name: 'core-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['core-service:8181']
  - job_name: 'auth-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: [ 'auth-service:8182' ]
  - job_name: 'course-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['course-service:8184']
  - job_name: 'code-assessment-service'
    scrape_interval: 1m
    metrics_path: '/actuator/metrics'
    static_configs:
      - targets: ['code-assessment-service:8183']